version: 0.2

phases:
  install:
    commands:
      - echo Installing .NET SDK
      - sudo yum install -y dotnet-sdk-8.0
  build:
    commands:
      - echo Building the solution...
      - dotnet build --configuration Release
      - dotnet publish -c Release -o ./bin/Release/net8.0/publish
  post_build:
    commands:
      - echo Build complete
      - echo Uploading build artifacts to S3...
      - aws s3 cp ./bin/Release/net8.0/publish s3://wmsbucket123/ --recursive
artifacts:
  files:
    - '**/*'
