version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing .NET SDK
      - wget https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
      - sudo rpm -Uvh packages-microsoft-prod.rpm
      - sudo yum install -y dotnet-sdk-8.0
  build:
    commands:
      - echo Building the solution...
      - dotnet restore --verbosity detailed
      - dotnet build --configuration Release --verbosity detailed
      - dotnet publish -c Release -o ./publish --verbosity detailed
      - echo "Contents of the working directory after publish:"
      - ls -la
      - echo "Contents of the publish directory:"
      - ls -la ./publish
  post_build:
    commands:
      - echo Build complete
      - echo Preparing deployment files...
      - cp appspec.yml ./publish/
      - mkdir -p ./publish/scripts
      - cp scripts/*.sh ./publish/scripts/
      - echo Uploading build artifacts to S3...
      - aws s3 cp ./publish s3://wmsbucket123/webapplication/ --recursive
      - echo "Contents of the S3 bucket after upload:"
      - aws s3 ls s3://wmsbucket123/webapplication/
artifacts:
  files:
    - '**/*'
  base-directory: 'publish'

